import {
  ObjectNotFoundError,
  ObjectStorageService,
} from "../lib/objectStorage";
import { cleanupOrderPdfs } from "../lib/orderPdfCleanup";
import { ORDER_PDF_LOCK_ID, ORDER_PDF_RETENTION_MS } from "../lib/orderPdfLifecycle";

type DatabasePool = typeof import("@workspace/db").pool;

export class FutureCleanupClockStorage extends ObjectStorageService {
  override deleteExpiredOrderPdf(file: Parameters<ObjectStorageService["deleteExpiredOrderPdf"]>[0], now: number) {
    // Project only the cleanup age comparison; App Storage metadata remains real.
    return super.deleteExpiredOrderPdf(file, now + 2 * ORDER_PDF_RETENTION_MS);
  }
}

export async function runCleanup(storage: ObjectStorageService): Promise<number> {
  try {
    return await cleanupOrderPdfs(storage);
  } catch {
    throw new Error("Real order PDF cleanup failed");
  }
}

export async function putSignedPdf(url: string, bytes: Buffer): Promise<void> {
  let response: Response;
  try {
    response = await fetch(url, {
      method: "PUT",
      headers: { "Content-Type": "application/pdf" },
      body: bytes,
      signal: AbortSignal.timeout(15_000),
    });
  } catch {
    throw new Error("Real App Storage signed upload request failed");
  }
  if (!response.ok) throw new Error(`Real App Storage PUT failed with status ${response.status}`);
}

export async function readObjectBytes(storage: ObjectStorageService, objectPath: string): Promise<Buffer> {
  try {
    const file = await storage.getObjectEntityFile(objectPath);
    const [bytes] = await file.download();
    return bytes;
  } catch {
    throw new Error("Real App Storage byte verification failed");
  }
}

export function createBarrier() {
  let signalReached!: () => void;
  let signalRelease!: () => void;
  const reached = new Promise<void>((resolve) => { signalReached = resolve; });
  let released = false;
  const releasePromise = new Promise<void>((resolve) => { signalRelease = resolve; });
  return {
    reached,
    async wait() {
      signalReached();
      if (!released) await releasePromise;
    },
    release() {
      released = true;
      signalRelease();
    },
  };
}

export async function createSchema(pool: DatabasePool, schema: string): Promise<void> {
  if (!/^pdf_lifecycle_[a-z0-9_]+$/.test(schema)) throw new Error("Unsafe integration schema name");
  await pool.query(`CREATE SCHEMA "${schema}"`);
  try {
    await pool.query(`
      CREATE TABLE "${schema}".order_sequences (
        prefix text PRIMARY KEY,
        last_number integer NOT NULL DEFAULT 0
      );
      CREATE TABLE "${schema}".orders (
        id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        order_number text NOT NULL UNIQUE,
        prefix text NOT NULL,
        zone_label text NOT NULL,
        kp_data jsonb NOT NULL,
        pdf_path text,
        created_at timestamp NOT NULL DEFAULT now()
      );
    `);
  } catch {
    try {
      await pool.query(`DROP SCHEMA IF EXISTS "${schema}" CASCADE`);
    } catch {
      throw new Error("Failed to create or clean up the isolated PDF integration schema");
    }
    throw new Error("Failed to create isolated PDF integration tables");
  }
}

export async function waitForAdvisoryLockWaiter(
  pool: DatabasePool,
  timeoutMs = 10_000,
): Promise<{ holderPid: number; waiterPid: number }> {
  const deadline = performance.now() + timeoutMs;
  while (performance.now() < deadline) {
    const query = {
      text: `
        SELECT pid, granted
        FROM pg_locks
        WHERE locktype = 'advisory'
          AND classid = 0::oid AND objid = $1::oid AND objsubid = 1
      `,
      values: [ORDER_PDF_LOCK_ID],
      query_timeout: 2_000,
    };
    const result = await pool.query<{ pid: number; granted: boolean }>(query);
    const holder = result.rows.find((row) => row.granted);
    const waiter = result.rows.find((row) => !row.granted);
    if (holder && waiter) {
      const holderPid = Number(holder.pid);
      const waiterPid = Number(waiter.pid);
      if (holderPid === waiterPid) throw new Error("Advisory lock holder and waiter share a backend");
      return { holderPid, waiterPid };
    }
    await new Promise((resolve) => setTimeout(resolve, 25));
  }
  throw new Error("Timed out waiting for a PostgreSQL advisory-lock waiter");
}

export async function within<T>(
  promise: Promise<T>,
  description: string,
  timeoutMs = 10_000,
): Promise<T> {
  let timer: ReturnType<typeof setTimeout> | undefined;
  try {
    return await Promise.race([
      promise,
      new Promise<never>((_, reject) => {
        timer = setTimeout(() => reject(new Error(`Timed out waiting for ${description}`)), timeoutMs);
      }),
    ]);
  } finally {
    if (timer) clearTimeout(timer);
  }
}

export class TestObjectManifest {
  private readonly paths = new Set<string>();

  constructor(private readonly storage: ObjectStorageService, private readonly namespace: string) {
    if (!/^[a-f0-9-]{36}$/.test(namespace)) throw new Error("Unsafe PDF integration namespace");
  }

  add(objectPath: string): void {
    if (!/^\/objects\/(?:uploads\/order-pdfs|order-pdfs)\/[a-f0-9-]{36}$/.test(objectPath)) {
      throw new Error("Refusing to track an object outside this PDF integration namespace");
    }
    this.paths.add(objectPath);
  }

  async removeCreatedObjects(): Promise<void> {
    for (const objectPath of this.paths) {
      const file = await this.storage.getObjectEntityFile(objectPath).catch((error: { code?: number }) => {
        if (error instanceof ObjectNotFoundError || error.code === 404) return null;
        throw new Error("Failed to locate a created PDF integration object");
      });
      if (!file) continue;
      try {
        const directory = this.storage.getPrivateObjectDir().replace(/^\/?[^/]+\//, "").replace(/^\/+/, "");
        if (!directory.endsWith(`integration-tests/pdf-lifecycle/${this.namespace}`)
          || !file.name.startsWith(`${directory.replace(/\/$/, "")}/`)) {
          throw new Error("Resolved object is outside this test's storage namespace");
        }
        const [metadata] = await file.getMetadata();
        if (!metadata.generation) throw new Error("Created test object has no generation");
        await file.delete({ ifGenerationMatch: metadata.generation });
      } catch (error) {
        if ((error as { code?: number }).code !== 404) {
          throw new Error("Failed to conditionally remove a created PDF integration object");
        }
      }
    }
    this.paths.clear();
  }
}