import { afterAll, beforeAll, describe, expect, it, vi } from "vitest";
import express, { type Request } from "express";
import request from "supertest";
import { sql } from "drizzle-orm";
import { ordersTable, orderSequencesTable } from "@workspace/db/schema";

const isolation = vi.hoisted(() => ({
  schema: `order_concurrency_${process.pid}_${Date.now()}_${Math.random().toString(16).slice(2)}`,
}));

// Keep the real PostgreSQL client and Drizzle queries, but isolate every
// route transaction from application data with a transaction-local schema.
vi.mock("@workspace/db", async (importOriginal) => {
  const actual = await importOriginal<typeof import("@workspace/db")>();
  const { sql } = await import("drizzle-orm");
  return {
    ...actual,
    db: {
      transaction: (callback: Parameters<typeof actual.db.transaction>[0]) =>
        actual.db.transaction(async (tx) => {
          await tx.execute(sql`SET LOCAL search_path TO ${sql.identifier(isolation.schema)}`);
          return callback(tx);
        }),
    },
  };
});

// Creating orders does not use storage; avoid initializing external services.
vi.mock("../lib/objectStorage", () => ({
  ObjectStorageService: class {},
  ObjectNotFoundError: class extends Error {},
  InvalidOrderPdfError: class extends Error {},
}));

import { db, pool } from "@workspace/db";
import router from "./orders";

const app = express();
app.use(express.json());
app.use((req, _res, next) => {
  req.session = {} as Request["session"];
  next();
});
app.use("/api", router);

describe("concurrent order creation with real PostgreSQL", () => {
  beforeAll(async () => {
    vi.stubEnv("SESSION_SECRET", "vitest-only-concurrent-order-secret");
    await pool.query(`CREATE SCHEMA "${isolation.schema}"`);
    await pool.query(`
      CREATE TABLE "${isolation.schema}".order_sequences (
        prefix text PRIMARY KEY,
        last_number integer NOT NULL DEFAULT 0
      );
      CREATE TABLE "${isolation.schema}".orders (
        id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        order_number text NOT NULL UNIQUE,
        prefix text NOT NULL,
        zone_label text NOT NULL,
        kp_data jsonb NOT NULL,
        pdf_path text,
        created_at timestamp NOT NULL DEFAULT now()
      );
    `);
  });

  afterAll(async () => {
    try {
      await pool.query(`DROP SCHEMA IF EXISTS "${isolation.schema}" CASCADE`);
    } finally {
      await pool.end();
      vi.unstubAllEnvs();
    }
  });

  it.each([
    { prefix: "С", width: 4, start: 0 },
    { prefix: "ДП", width: 3, start: 41 },
    { prefix: "ТВ", width: 3, start: 998 },
  ])("saves every simultaneous request for $prefix with unique sequential numbers", async ({ prefix, width, start }) => {
    if (start) {
      await db.transaction((tx) =>
        tx.insert(orderSequencesTable).values({ prefix, lastNumber: start }),
      );
    }
    const count = 20;
    const responses = await Promise.all(Array.from({ length: count }, (_, index) =>
      request(app).post("/api/orders").send({
        prefix,
        zoneLabel: `Concurrent calculation ${index}`,
        kpData: { calculationIndex: index },
      }),
    ));

    expect(responses.map((response) => response.status)).toEqual(Array(count).fill(201));
    const numbers = responses.map((response) => response.body.orderNumber);
    expect(new Set(numbers).size).toBe(count);
    expect(new Set(responses.map((response) => response.body.id)).size).toBe(count);
    expect(numbers.sort()).toEqual(
      Array.from({ length: count }, (_, i) => `${prefix}-${String(start + i + 1).padStart(width, "0")}`).sort(),
    );

    const { orders, sequence } = await db.transaction(async (tx) => ({
      orders: await tx.select().from(ordersTable),
      sequence: await tx.select().from(orderSequencesTable),
    }));
    const saved = orders.filter((order) => order.prefix === prefix);
    expect(saved).toHaveLength(count);
    expect(saved.map((order) => order.orderNumber).sort()).toEqual(numbers);
    expect(saved.map((order) => (order.kpData as { calculationIndex: number }).calculationIndex).sort((a, b) => a - b))
      .toEqual(Array.from({ length: count }, (_, i) => i));
    expect(sequence.find((row) => row.prefix === prefix)?.lastNumber).toBe(start + count);
  });

  it("rolls back the counter when saving the order fails", async () => {
    await db.transaction(async (tx) => {
      await tx.insert(orderSequencesTable).values({ prefix: "К", lastNumber: 0 });
      await tx.insert(ordersTable).values({
        prefix: "К", orderNumber: "К-001", zoneLabel: "Existing order", kpData: {},
      });
    });
    const response = await request(app).post("/api/orders").send({
      prefix: "К", zoneLabel: "Rejected duplicate", kpData: {},
    });
    expect(response.status).toBe(500);
    await db.transaction(async (tx) => {
      const sequences = await tx.select().from(orderSequencesTable);
      expect(sequences.find((row) => row.prefix === "К")?.lastNumber).toBe(0);
      const orders = await tx.select().from(ordersTable);
      expect(orders.filter((order) => order.prefix === "К")).toHaveLength(1);
    });
  });
});